### ISSUE TITLE
Erro ao Adicionar item a uma Fatura

### ISSUE THREAD

**Issue by pauloneda** [odoo-brazil/l10n-brazil#114]
Módulo NFe instalado e Módulo Analítico também instalado

Ao abrir a tela para adicionar PRODUTO ou no on_change do produto.
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 5888, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/odoo/openerp/models.py", line 5806, in _onchange_eval
    method_res = getattr(self._model, method)(*args)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
TypeError: product_id_change() takes at most 15 arguments (17 given)

**Comment by pauloneda** [comment]
File "/opt/odoo/odoo/addons/account_analytic_plans/account_analytic_plans.py", line 306, in product_id_change
    res_prod = super(account_invoice_line, self).product_id_change(cr, uid, ids, product, uom_id, qty, name, type, partner_id, fposition_id, price_unit, currency_id, company_id=company_id, context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/account_analytic_default/account_analytic_default.py", line 80, in product_id_change
    res_prod = super(account_invoice_line, self).product_id_change(cr, uid, ids, product, uom_id, qty, name, type, partner_id, fposition_id, price_unit, currency_id=currency_id, company_id=company_id, context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/l10n-brazil/l10n_br_account/account_invoice.py", line 537, in product_id_change
    product, parent_fiscal_category_id)
  File "/opt/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 442, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/l10n-brazil/l10n_br_account/account_fiscal_position_rule.py", line 164, in product_fiscal_category_map
    cr, uid, product_id, ['product_tmpl_id'])['product_tmpl_id'][0]
TypeError: list indices must be integers, not str

**Comment by pauloneda** [comment]
@danimaribeiro 

L10N_BR_ACCOUNT/ACCOUNT_FISCAL_POSITION_RULE linha 163 alterado para 
        product_tmpl_id = self.pool.get('product.product').read(
            cr, uid, product_id, ['product_tmpl_id'])[0]['product_tmpl_id'][0]

It's work fine !!
