### ISSUE TITLE
 Erro ao alterar Categoria Fiscal

### ISSUE THREAD

**Issue by marceloeng** [odoo-brazil/l10n-brazil#24]
Ao fazer uma cotação ou pedido de venda, na aba "Outras Informações", se for feita uma alteração de Categoria Fiscal, aparece o seguinte erro:

Odoo Server Error

Traceback (most recent call last):
File "/opt/odoo/openerp/http.py", line 530, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/opt/odoo/openerp/http.py", line 567, in dispatch
result = self._call_function(**self.params)
File "/opt/odoo/openerp/http.py", line 303, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
return f(dbname, *args, **kwargs)
File "/opt/odoo/openerp/http.py", line 300, in checked_call
return self.endpoint(*a, **kw)
File "/opt/odoo/openerp/http.py", line 796, in __call__
return self.method(*args, **kw)
File "/opt/odoo/openerp/http.py", line 396, in response_wrap
response = f(*args, **kw)
File "/opt/odoo/addons/web/controllers/main.py", line 937, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/opt/odoo/addons/web/controllers/main.py", line 929, in _call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
File "/opt/odoo/openerp/api.py", line 241, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/openerp/api.py", line 363, in old_api
result = method(recs, *args, **kwargs)
File "/opt/odoo/openerp/models.py", line 5864, in onchange
record._onchange_eval(name, field_onchange[name], result)
File "/opt/odoo/openerp/models.py", line 5782, in _onchange_eval
method_res = getattr(self._model, method)(*args)
File "/opt/odoo/openerp/api.py", line 241, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/localizacao/l10n-brazil/l10n_br_sale/sale.py", line 223, in onchange_fiscal_category_id
return fp_rule_obj.apply_fiscal_mapping(cr, uid, result, **kwargs)
TypeError: apply_fiscal_mapping() takes exactly 2 arguments (9 given)

Mesmo após o erro, o sistema fica marcado aquele que foi escolhido.

**Comment by mileo** [comment]
?

**Comment by mileo** [comment]
Quer ajuda ai?

**Comment by marceloeng** [comment]
Boa noite Luis,

O Danimar pediu para eu adicionar esse erro como um bug no gituhub. 
Ocorre que eu somente consigo colocar como Issue, provavelmente por não 
ser um dos mantenedores do código.


Abraço,
*Marcelo Costa
*Engenheiro de Computação*
*
------------------------------------------------------------------------
*
Soluções convergentes em infraestrutura de TI*
Telefone: (51) 3022.5100
E-mail:marcelo@comdesk.com.br
Web-Site: www.comdesk.com.br

**Comment by danimaribeiro** [comment]
Pode ser issue mesmo.

-----Mensagem Original-----
De: "Marcelo Costa" <notifications@github.com>
Enviada em: ‎27/‎05/‎2015 00:03
Para: "odoo-brazil/l10n-brazil" <l10n-brazil@noreply.github.com>
Assunto: Re: [l10n-brazil]  Erro ao alterar Categoria Fiscal (#24)

Boa noite Luis,

O Danimar pediu para eu adicionar esse erro como um bug no gituhub. 
Ocorre que eu somente consigo colocar como Issue, provavelmente por não 
ser um dos mantenedores do código.


Abraço,
*Marcelo Costa
*Engenheiro de Computação*
*
------------------------------------------------------------------------
*
Soluções convergentes em infraestrutura de TI*
Telefone: (51) 3022.5100
E-mail:marcelo@comdesk.com.br
Web-Site: www.comdesk.com.br

**Comment by mileo** [comment]
exato https://help.github.com/articles/permission-levels-for-an-organization-repository/

**Comment by marceloeng** [comment]
Legal...

Abraço e obrigado.
*Marcelo Costa
*Engenheiro de Computação*
*
------------------------------------------------------------------------
*
Soluções convergentes em infraestrutura de TI*
Telefone: (51) 3022.5100
E-mail:marcelo@comdesk.com.br
Web-Site: www.comdesk.com.br
