### ISSUE TITLE
Erro ao criar uma "Solicitação para cotação" (fornecedores)

### ISSUE THREAD

**Issue by carlos-korovsky** [odoo-brazil/l10n-brazil#88]
Ao adicionar um produto em uma "Solicitação para cotação" de Fornecedores, ocorre o seguinte erro ao selecionar a "Categoria Fiscal" / "Posição fiscal" do produto. Neste caso é um produto para revenda (Compras para revenda), foram configuradas as "Regras de posição fiscal", categoria fiscal e posição fiscal (aquisição dentro do estado).

   Observações:
      - Com o produto selecionado, selecionando uma categoria fiscal incorreta (compras para industrialização), o sistema deixa a posição fiscal em branco, mesmo tentando adicionar manualmente.
      - Sem que o produto seja selecionado, é possível configurar a categoria fiscal/posição fiscal.
      - As cotações para cliente estão funcionando corretamente.
      - Odoo 8.0 via github/odoo; Localização brasileira e demais dependências via github/odoo-brazil (Repositório local atualizado 11/09/2015)
Descrição no forum:
https://groups.google.com/forum/#!topic/openerp-brasil/drZJ1ON22-s

Segue o erro:
```python
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo.git/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo.git/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo.git/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo.git/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo.git/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo.git/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo.git/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo.git/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo.git/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo.git/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo.git/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo.git/openerp/models.py", line 5888, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo.git/openerp/models.py", line 5806, in _onchange_eval
    method_res = getattr(self._model, method)(*args)
  File "/opt/odoo.git/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo.git/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/l10n-brazil.git/l10n_br_purchase/purchase.py", line 385, in onchange_fiscal_position
    obj_fposition, taxes, context=context)
  File "/opt/odoo.git/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
TypeError: map_tax() takes exactly 2 arguments (4 given)
```

**Comment by mstuttgart** [comment]
@carlos-korovsky Sabe se alguém encontrou uma solução para esse erro?

**Comment by mileo** [comment]
A sobrescrita dos metodos deve estar errada, de uma olhada no sale.py/stock/invoice como esta sendo feito.

**Comment by mstuttgart** [comment]
@mileo , por gentileza, tem como ser mais especifico com relação ao arquivo?

**Comment by carlos-korovsky** [comment]
@mstuttgart até o presente momento o erro está persistindo.

**Comment by carlos-korovsky** [comment]
@mstuttgart até o presente momento o erro está persistindo. Desculpe, acabei fechando a issue sem querer.

**Comment by mstuttgart** [comment]
Eu arrumei uma solução temporária para o erro aqui: [kmee fix](https://github.com/kmee/l10n-brazil/tree/fix/onchange_fiscal_position_purchase_order_line)  
Assim como o @mileo comentou, o problema está na migração do método *onchange_fiscal_position*
Eu voltei o código para versão 7, igual ao que está presente no módulo *l10n_br_sale/sale.py*.

Assim que puder, vou dar uma olhada pra ver se encontro o que está de errado no método migrado.

**Comment by mstuttgart** [comment]
@carlos-korovsky Segue correção para a V8. https://github.com/odoo-brazil/l10n-brazil/issues/130

**Comment by mileo** [comment]
Qual versão do account-fiscal-rule vcs estão usando?

**Comment by mstuttgart** [comment]
Account Fiscal Rule: 
* Repo: Odoo-Brazil https://github.com/odoo-brazil/account-fiscal-rule
* Branch: 8.0
* Ultimo Commit: 2015-09-01 1a2384d Merge pull request #2 from Trust-Code/feature/melhorias_view_regras

**Comment by mileo** [comment]
Analisando o sale e o purchase do account-fiscal-rule eles estão iguais, mas o que vc pode olhar é se as chamadas estão compatíveis como no l10n_br_sale e o account_fiscal_position_rule_sale:<br><br>https://github.com/odoo-brazil/account-fiscal-rule/blob/8.0/account_fiscal_position_rule_purchase/purchase.py<br>https://github.com/odoo-brazil/l10n-brazil/blob/8.0/l10n_br_purchase/purchase.py<br><br>https://github.com/odoo-brazil/account-fiscal-rule/blob/8.0/account_fiscal_position_rule_sale/sale.py<br>https://github.com/odoo-brazil/l10n-brazil/blob/8.0/l10n_br_sale/sale.py#L352<br><br>OBS: Lembrando que o super do purchase é chamado de forma diferente.<br><br><br> 

- Luis Felipe Miléo 
Gerência de Implementação 
+55 11 4063-9872 (SP) 
+55 21 4063-8872 (RJ) 
mileo @kmee.com.br 
kmee.com.br 
Parceiro oficial:

**Comment by mstuttgart** [comment]
@mileo vou dar uma olhada nisso. Obrigado.
